In [1]:
#regresion lineal
#el paquete scikit-learn para regresion lienal y la seleccion de rasgos

In [5]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas
import numpy 

In [6]:
data=pandas.read_csv(r"D:\Estudiar\Python\MLData\ads\Advertising.csv")

In [7]:
feature_cols=["TV","Radio","Newspaper"]

In [8]:
x=data[feature_cols] #candidatas a ser variables predictoras
y=data["Sales"] #variable a predecir

In [9]:
estimator=SVR(kernel="linear")
selector=RFE(estimator,2,step=1)
selector=selector.fit(x,y)

In [11]:
selector.support_

array([ True,  True, False])

In [12]:
selector.ranking_

array([1, 1, 2])

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
x_pred=x[["TV","Radio"]]

In [16]:
lm=LinearRegression()
lm.fit(x_pred,y)

LinearRegression()

In [18]:
lm.intercept_ #alpha

2.921099912405138

In [19]:
lm.coef_ #coeficientes de cada variable predictora

array([0.04575482, 0.18799423])

In [20]:
lm.score(x_pred,y) #valor de R**2 ajustado

0.8971942610828957