In [1]:
#El metodo de k-means

In [2]:
import numpy

In [4]:
data=numpy.random.random(90).reshape(30,3)

In [7]:
c1=numpy.random.choice(range(len(data)))
c2=numpy.random.choice(range(len(data)))
clust_centera=numpy.vstack([data[c1],data[c2]])
clust_centera

array([[0.47729459, 0.34348936, 0.02035742],
       [0.74349202, 0.80857665, 0.87586523]])

In [9]:
from scipy.cluster.vq import vq

In [10]:
vq(data,clust_centera)

(array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0]),
 array([0.50608765, 0.57198938, 0.64416897, 0.61661862, 0.22070955,
        0.2247252 , 0.40832587, 0.63060995, 0.28259021, 0.48817805,
        0.60491079, 0.81654421, 0.46880467, 0.31422801, 0.58152232,
        0.26486703, 0.59399397, 0.5070503 , 0.393663  , 0.        ,
        0.55698589, 0.        , 0.68479181, 0.3867608 , 0.52599412,
        0.39364212, 0.73952111, 0.68293147, 0.44290467, 0.4775531 ]))

In [11]:
from scipy.cluster.vq import kmeans

In [12]:
kmeans(data,clust_centera) #valores de los varicentros #el valor final es la suma de los errores al cuadrado

(array([[0.63919966, 0.45003494, 0.19407585],
        [0.38483694, 0.45412455, 0.72839013]]),
 0.35022034086986803)

In [13]:
kmeans(data,2) #indicando el numero de clusters

(array([[0.63919966, 0.45003494, 0.19407585],
        [0.38483694, 0.45412455, 0.72839013]]),
 0.35022034086986803)