In [6]:
import numpy
from sklearn.datasets import load_breast_cancer

In [7]:
data=load_breast_cancer()
X, y = data.data, data.target

In [8]:
X=data.data[:,:4]
X.shape

(569, 4)

array([[  17.99,   10.38,  122.8 , 1001.  ],
       [  20.57,   17.77,  132.9 , 1326.  ],
       [  19.69,   21.25,  130.  , 1203.  ],
       [  11.42,   20.38,   77.58,  386.1 ],
       [  20.29,   14.34,  135.1 , 1297.  ],
       [  12.45,   15.7 ,   82.57,  477.1 ],
       [  18.25,   19.98,  119.6 , 1040.  ],
       [  13.71,   20.83,   90.2 ,  577.9 ],
       [  13.  ,   21.82,   87.5 ,  519.8 ],
       [  12.46,   24.04,   83.97,  475.9 ]])

In [12]:
#Para entrenar modelos de deep learning es importante que las variables esten en la misma escala, por ello vamos a estandarizar la variables independientes

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
x_estandarizador=StandardScaler()
X_std=x_estandarizador.fit_transform(X)

In [15]:
#En primer lugar, tenemos que definir una capa, creamos la clase Layer que tiene una dimension de entrada, una de salida, y una funcion de activacion
#inicialmente sus pesos se generan al azar

In [32]:
class Layer:
    def __init__(self, dim_input, dim_output, fn_activacion, nombre):
        self.dim_input=dim_input
        self.dim_output=dim_output
        self.generar_pesos((dim_output,dim_input))
        self.generar_bias(dim_output)
        self.fn_activacion=fn_activacion
        self.nombre=nombre

    def __repr__(self):
        return """
        Capa {}. tamaño input: {}. tamaño output: {}.
        pesos: {}
        bias: {}
        """.format(self.nombre, self.dim_input, self.dim_output, self.w, self.b)

    def generar_pesos(self, dimensiones):
        self.w=numpy.random.random(dimensiones)

    def generar_bias(self, dim_output):
        self.b=numpy.random.random((dim_output, ))

    def activar(self, x):
        return self.fn_activacion((self.w @ x) + self.b)

In [33]:
#PAra hacer propagacion hacia adelante necesitamos la funcion de activacion, en este ejemplo se usara la funcion sigmoide como activacion de la capa oculta

In [34]:
def fn_sigmoide(x):
    return 1/(1+numpy.exp(-x))

In [35]:
n_input=4
n_oculta=5
n_output=1

In [36]:
capa_oculta=Layer(n_input, n_oculta, fn_sigmoide, "oculta")
capa_salida=Layer(n_oculta, n_output, fn_sigmoide, "salida")

In [37]:
class RedNeuronal:
    def __init__(self):
        self.layers=[]

    def add_layer(self, layer):
        self.layers.append(layer)
    
    def forward(self, x):
        print("""
        input: {}
        """.format(x))
        for layer in self.layers:
            x=layer.activar(x)
            print(layer)
            print("""
            outout: {}
            """.format(x))
        return x

In [38]:
red=RedNeuronal()

In [39]:
red.add_layer(capa_oculta)
red.add_layer(capa_salida)

In [40]:
indice_aleatorio=numpy.random.permutation(X.shape[0])

x0=X_std[indice_aleatorio[0]]
y0=y[indice_aleatorio[0]]
print(x0, y0)

[-1.03304249e+00  8.17949781e-05 -1.01159150e+00 -9.06668923e-01] 1


In [41]:
red.forward(x0)


        input: [-1.03304249e+00  8.17949781e-05 -1.01159150e+00 -9.06668923e-01]
        

        Capa oculta. tamaño input: 4. tamaño output: 5.
        pesos: [[0.96571167 0.44207891 0.78079633 0.68541454]
 [0.66698232 0.85375703 0.90501534 0.26267646]
 [0.35855297 0.10233853 0.46103217 0.20151105]
 [0.68094106 0.50298556 0.51844755 0.02688474]
 [0.62269651 0.06379982 0.44328439 0.33572092]]
        bias: [0.88647321 0.47077813 0.95181834 0.1456406  0.78321969]
        

            outout: [0.17910797 0.2023228  0.483093   0.24850679 0.35140764]
            

        Capa salida. tamaño input: 5. tamaño output: 1.
        pesos: [[0.65530272 0.23113074 0.2360328  0.53539186 0.85015431]]
        bias: [0.38824631]
        

            outout: [0.74992349]
            


array([0.74992349])

<bound method Layer.__repr__ of 
        Capa oculta. tamaño input: 4. tamaño output: 5.
        pesos: [[0.35702323 0.90929398 0.31604438 0.30255787 0.05205402]
 [0.61942791 0.67051813 0.32121493 0.75394678 0.1642054 ]
 [0.8281652  0.31073093 0.07389647 0.88047941 0.21336749]
 [0.61804184 0.83928999 0.8675924  0.7897887  0.15216925]]
        bias: [0.38899438 0.93693415 0.4520474  0.77804805 0.06172713]
        >