In [2]:
import tensorflow as tf

In [3]:
pi = tf.constant(3.14159, name = "pi", dtype= tf.float32)

In [4]:
M = tf.Variable([[3, 1], [2, 4]])
K = tf.Variable([[1, 2], [3, 4]])
KM = tf.matmul(K, M)
print(KM)

tf.Tensor(
[[ 7  9]
 [17 19]], shape=(2, 2), dtype=int32)


In [5]:
print(pi)
print(M)

tf.Tensor(3.14159, shape=(), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 1],
       [2, 4]])>


In [6]:
tensor = tf.ones(shape=(3, 4), dtype=tf.float32)

In [7]:
print(tensor)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)


In [8]:
tensor = tf.transpose(tensor)
print(tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [9]:
ints = tf.Variable(4, dtype=tf.int32)
floats = tf.cast(ints, dtype=tf.float32)

In [12]:
print(ints)
print(floats)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=4>
tf.Tensor(4.0, shape=(), dtype=float32)


In [16]:
variable = tf.Variable(tensor, dtype=tf.float32)

In [19]:
variable[0].assign([0, 1, 2])
variable

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[0., 1., 2.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [25]:
variable[0, 1].assign(5)
variable

<tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[0., 5., 2.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [37]:
t3 = tf.constant([[[1, 3, 5, 7],
                   [9, 11, 13, 15]],
                  [[17, 19, 21, 23],
                   [25, 27, 29, 31]]
                  ])

print(tf.slice(t3,
               begin=[1, 1, 0],
               size=[1, 1, 1]))

tf.Tensor([[[25]]], shape=(1, 1, 1), dtype=int32)


In [38]:
t3

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]],

       [[17, 19, 21, 23],
        [25, 27, 29, 31]]])>

In [39]:
t3[0, :, :]

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])>

In [61]:
t1 = tf.constant([-3,1], dtype=tf.float32)

In [62]:
tf.less(t1,0)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [49]:
fn = lambda t: 0 if tf.less(t, 0) else 1

In [64]:
tf.map_fn(fn=lambda t: tf.range(t, t + 3), elems=tf.constant([3, 5, 2]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 4, 5],
       [5, 6, 7],
       [2, 3, 4]])>

In [67]:
tf.map_fn(fn=lambda t: 0 if tf.less(t, 0) else 1, elems=tf.constant([-3, 5, 2]))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 1])>

In [74]:
def hardlim(t):
    return tf.constant(0, dtype=tf.float16) if tf.less(t, 0) else tf.constant(1, dtype=tf.float16)

In [75]:
tf.map_fn(fn=hardlim, elems=tf.Variable([-3, 5, 2], dtype=tf.float16))

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([0., 1., 1.], dtype=float16)>

In [89]:
Patterns = tf.Variable(tf.zeros((2, 4), dtype=tf.float16))
Patterns

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float16, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)>

In [90]:
Patterns[0, :].assign(tf.Variable([0, 1, 2, 3], dtype=tf.float16))

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=float16, numpy=
array([[0., 1., 2., 3.],
       [0., 0., 0., 0.]], dtype=float16)>

In [2]:
random_1 = tf.random.Generator.from_seed(7)

In [4]:
random = random_1.normal(shape=(3, 2))
random

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.15951356, -0.2555016 ],
       [ 1.4733889 , -1.8130383 ],
       [-0.693323  ,  0.61685944]], dtype=float32)>

In [6]:
not_shuffled = tf.Variable([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]], dtype=tf.float32)

In [7]:
shuffled = tf.random.shuffle(not_shuffled)
tf.random.shuffle()

In [10]:
print(not_shuffled.numpy())
print(shuffled.numpy())

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [7. 8. 9.]
 [4. 5. 6.]]


In [12]:
shuffled.ndim

2

In [13]:
tf1 = tf.ones(shape=(3, 2, 1, 4))

In [14]:
tf1

<tf.Tensor: shape=(3, 2, 1, 4), dtype=float32, numpy=
array([[[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]]], dtype=float32)>

In [15]:
tf1[0, 0, :, :]

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 1., 1.]], dtype=float32)>

In [1]:
import tensorflow_probability as tfp

In [3]:
t = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float16)

In [4]:
tf.math.reduce_mean(t)

<tf.Tensor: shape=(), dtype=float16, numpy=3.5>

In [10]:
some_list = [0, 1]

In [12]:
one_hot = tf.one_hot(some_list, depth=2)

In [17]:
T = tf.concat([one_hot, one_hot, one_hot], axis=1)

In [18]:
T

<tf.Tensor: shape=(2, 6), dtype=float32, numpy=
array([[1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1.]], dtype=float32)>