In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def make_variables(x, y, initializer):
    return tf.Variable(initializer(shape=[x, y], dtype=tf.float16))

In [3]:
num_patterns = 4
num_inputs = 2
num_neurons = 4
P = tf.constant([[0, 0, 1, 1],
                 [0, 1, 0, 1]], dtype=tf.float16)
T = tf.constant([[1, 1, 1, 1],
                 [1, 1, 1, 1],
                 [1, 1, 1, 1],
                 [1, 1, 1, 1]], dtype=tf.float16)
init = tf.random_uniform_initializer(minval=-1., maxval=1.)
W = make_variables(num_neurons, num_inputs, init)
b = make_variables(num_neurons, 1, init)
dw = tf.zeros([1, 2], dtype=tf.float16)
e = tf.Variable(0, dtype=tf.float16)
sum_e = tf.Variable(0, dtype=tf.float16)

In [4]:
def hardlim(var: tf.Variable):
    res = np.zeros(var.numpy().shape)
    for i, row in enumerate(var.numpy()):
        for j, col in enumerate(row):
            res[i][j] = 1 if col > 0 else 0
    return tf.Variable(res, dtype=tf.float16, shape=(var.numpy().shape))

In [5]:
for _ in range(10):
    output = tf.subtract(tf.matmul(W, P), b)
    a = hardlim(output)
    e = tf.subtract(T, a)
    dw = tf.matmul(e, tf.transpose(P))
    sum_e = tf.reduce_sum(e, 1, keepdims=True)
    W = tf.add(W, dw)
    b = tf.subtract(b, sum_e)
    print(sum(sum_e.numpy()))

[3.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]
[0.]


In [6]:
output = tf.subtract(tf.matmul(W, P), b)
output

<tf.Tensor: shape=(4, 4), dtype=float16, numpy=
array([[2.477 , 3.652 , 3.812 , 4.99  ],
       [0.1562, 0.6367, 0.922 , 1.402 ],
       [1.277 , 1.734 , 1.994 , 2.451 ],
       [0.625 , 0.707 , 0.787 , 0.869 ]], dtype=float16)>

In [8]:
a = hardlim(output)
a

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float16, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)>

In [9]:
 e = tf.subtract(T, a)
 e

<tf.Tensor: shape=(4, 4), dtype=float16, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float16)>