In [1]:
import tensorflow as tf

In [5]:
@tf.function
def add(a, b):
    sa = a + a
    sb = b + b
    return sa + sb

In [7]:
add(5, 6)

<tf.Tensor: shape=(), dtype=int32, numpy=22>

In [8]:
print(tf.autograph.to_code(add.python_function))

def tf__add(a, b):
    with ag__.FunctionScope('add', 'fscope', ag__.ConversionOptions(recursive=True, user_requested=True, optional_features=(), internal_convert_user_code=True)) as fscope:
        do_return = False
        retval_ = ag__.UndefinedReturnValue()
        sa = (ag__.ld(a) + ag__.ld(a))
        sb = (ag__.ld(b) + ag__.ld(b))
        try:
            do_return = True
            retval_ = (ag__.ld(sa) + ag__.ld(sb))
        except:
            do_return = False
            raise
        return fscope.ret(retval_, do_return)



In [2]:
def linear_layer(x):
    return 2*x + 1

@tf.function
def deep_net(x):
    return tf.nn.relu(linear_layer(x))

In [3]:
deep_net(tf.constant((1, 2, 3)))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7])>

In [4]:
@tf.function
def f(x):
    print("Traced with", x)
    tf.print("Executed with", x)
for i in range(5):
    f(2)

Traced with 2
Executed with 2
Executed with 2
Executed with 2
Executed with 2
Executed with 2


In [8]:
v = tf.Variable(1.0)
@tf.function
def f(x):
    #v = tf.Variable(1.0)
    v.assign_add(x)
    return v
f(2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>